# Starbucks: Analyze-a-Coffee

## Business Questions

The purpose of the analysis is to examine how Starbucks’ customers respond to an offer whether a BOGO or Discount is the offer. Not all customers have the same incentives to view an offer and then make a transaction to complete the offer. Many factors play an important role in impacting how customers make purchasing decisions; for instance, some customers prefer offers that allow them to collect more and more stars toward getting exclusive perks or even free products. Sometimes, customers at a particular age group, prefer an offer different than what another group prefers. Moreover, we should keep in mind that female customers may react to an offer is different than how male customers do. Many aspects can be investigated and analyzed to find answers to such questions. All of that would help Starbucks to target its customers, and then personalizes and customizes the offers it sends depending on who are the audience. Many questions can be asked; here is some of what we are going to investigate:

1. What is the number of customers who received at least one offer? 
2. Who usually spend more at Starbucks, female or male?
3. For the customers who spend more; Who makes more income per year?
4. How old are most of Starbucks customers with respect to gender?
5. How much do customers spend at any time since the start of an offer?
6. Can we find the most popular offer by an age group or a gender, then compare it to other offers, or even another age group?
7. Which offer has made the most for Starbucks? Is there a difference between BOGO offers and Discount offers? If so, Do male customers react the same as female customers do for any of the two offer types?

In [1]:
# importing libraries
import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as plt

# magic word for producing visualizations in notebook
%matplotlib inline

import plotly.plotly as py #for creating interactive data visualizations
import plotly.graph_objs as go
import plotly.tools as tls
py.sign_in('salitr', 'bZDLctwyhomQu8cTsfXj') #API key has been removed for security
from plotly.offline import download_plotlyjs,init_notebook_mode,plot,iplot #to work with data visualization offline
init_notebook_mode(connected=True)
import cufflinks as cf #connects Plotly with pandas to produce the interactive data visualizations
cf.go_offline()

from IPython.display import Image

In [4]:
# reading the saved files from PART 1

profile_clean = pd.read_csv('profile_clean.csv', sep=';')
transactions = pd.read_csv('transactions.csv', sep=';')
offers = pd.read_csv('offers.csv', sep=';')
offers_comparsion = pd.read_csv('offers_comparsion.csv', sep=';')

### 2.2 Part 2


In [7]:
# merging all three datasets to have a complete, clean dataset 

full_data = pd.merge(pd.merge(pd.merge(profile_clean, 
                                  transactions, on='customer_id'), 
                         offers, on='customer_id'), 
                offers_comparsion, on='offer_id')

In [8]:
# locking at the full datasets

full_data

customer_id  age gender    income  \
0        0610b486422d4921ae7d2bf64640c50b   55      F  112000.0   
1        0610b486422d4921ae7d2bf64640c50b   55      F  112000.0   
2        0610b486422d4921ae7d2bf64640c50b   55      F  112000.0   
3        0610b486422d4921ae7d2bf64640c50b   55      F  112000.0   
4        0610b486422d4921ae7d2bf64640c50b   55      F  112000.0   
5        0610b486422d4921ae7d2bf64640c50b   55      F  112000.0   
6        78afa995795e4d85b5d9ceeca43f5fef   75      F  100000.0   
7        78afa995795e4d85b5d9ceeca43f5fef   75      F  100000.0   
8        78afa995795e4d85b5d9ceeca43f5fef   75      F  100000.0   
9        78afa995795e4d85b5d9ceeca43f5fef   75      F  100000.0   
10       78afa995795e4d85b5d9ceeca43f5fef   75      F  100000.0   
11       78afa995795e4d85b5d9ceeca43f5fef   75      F  100000.0   
12       78afa995795e4d85b5d9ceeca43f5fef   75      F  100000.0   
13       78afa995795e4d85b5d9ceeca43f5fef   75      F  100000.0   
14       78afa995795e4d85b5d9ceeca43f5fef   75      F  100000.0   
15       78afa995795e4d85b5d9ceeca43f5fef   75      F  100000.0   
16       78afa995795e4d85b5d9ceeca43f5fef   75      F  100000.0   
17       78afa995795e4d85b5d9ceeca43f5fef   75      F  100000.0   
18       78afa995795e4d85b5d9ceeca43f5fef   75      F  100000.0   
19       78afa995795e4d85b5d9ceeca43f5fef   75      F  100000.0   
20       78afa995795e4d85b5d9ceeca43f5fef   75      F  100000.0   
21       78afa995795e4d85b5d9ceeca43f5fef   75      F  100000.0   
22       78afa995795e4d85b5d9ceeca43f5fef   75      F  100000.0   
23       78afa995795e4d85b5d9ceeca43f5fef   75      F  100000.0   
24       78afa995795e4d85b5d9ceeca43f5fef   75      F  100000.0   
25       78afa995795e4d85b5d9ceeca43f5fef   75      F  100000.0   
26       78afa995795e4d85b5d9ceeca43f5fef   75      F  100000.0   
27       e2127556f4f64592b11af22de27a7932   68      M   70000.0   
28       e2127556f4f64592b11af22de27a7932   68      M   70000.0   
29       e2127556f4f64592b11af22de27a7932   68      M   70000.0   
...                                   ...  ...    ...       ...   
1143184  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143185  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143186  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143187  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143188  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143189  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143190  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143191  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143192  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143193  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143194  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143195  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143196  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143197  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143198  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143199  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143200  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143201  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143202  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143203  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143204  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143205  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143206  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143207  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143208  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143209  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143210  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143211  9dc1421481194dcd9400aec7c9ae6366   83      F   50000.0   
1143212  9

In [9]:
# renaming the time hours of the transactions to be distinguished from the time of offers 
full_data.rename(columns={'time(hours)_x': 'time_of_transaction(hours)'}, inplace=True)

In [10]:
# a function to recreate the ids columns to be easy ids to use and communicate

def id_mapper(df, column):
    coded_dict = dict()
    cter = 1
    id_encoded = []
    
    for val in df[column]:
        if val not in coded_dict:
            coded_dict[val] = cter
            cter+=1
        
        id_encoded.append(coded_dict[val])
    return id_encoded

cid_encoded = id_mapper(full_data, 'customer_id')
full_data['customer_id'] = cid_encoded

oid_encoded = id_mapper(full_data, 'offer_id')
full_data['offer_id'] = oid_encoded

To make even easier to communicate the customers and offers ids, they have been mapped to be represented by numbers instead of hashes or codes.

In [11]:
# locking at the full datasets after recreating the ids

full_data

customer_id  age gender    income membership_start membership_period  \
0                  1   55      F  112000.0       2017-07-15           2017-07   
1                  1   55      F  112000.0       2017-07-15           2017-07   
2                  1   55      F  112000.0       2017-07-15           2017-07   
3                  1   55      F  112000.0       2017-07-15           2017-07   
4                  1   55      F  112000.0       2017-07-15           2017-07   
5                  1   55      F  112000.0       2017-07-15           2017-07   
6                  2   75      F  100000.0       2017-05-09           2017-05   
7                  2   75      F  100000.0       2017-05-09           2017-05   
8                  2   75      F  100000.0       2017-05-09           2017-05   
9                  2   75      F  100000.0       2017-05-09           2017-05   
10                 2   75      F  100000.0       2017-05-09           2017-05   
11                 2   75      F  100000.0       2017-05-09           2017-05   
12                 2   75      F  100000.0       2017-05-09           2017-05   
13                 2   75      F  100000.0       2017-05-09           2017-05   
14                 2   75      F  100000.0       2017-05-09           2017-05   
15                 2   75      F  100000.0       2017-05-09           2017-05   
16                 2   75      F  100000.0       2017-05-09           2017-05   
17                 2   75      F  100000.0       2017-05-09           2017-05   
18                 2   75      F  100000.0       2017-05-09           2017-05   
19                 2   75      F  100000.0       2017-05-09           2017-05   
20                 2   75      F  100000.0       2017-05-09           2017-05   
21                 2   75      F  100000.0       2017-05-09           2017-05   
22                 2   75      F  100000.0       2017-05-09           2017-05   
23                 2   75      F  100000.0       2017-05-09           2017-05   
24                 2   75      F  100000.0       2017-05-09           2017-05   
25                 2   75      F  100000.0       2017-05-09           2017-05   
26                 2   75      F  100000.0       2017-05-09           2017-05   
27                 3   68      M   70000.0       2018-04-26           2018-04   
28                 3   68      M   70000.0       2018-04-26           2018-04   
29                 3   68      M   70000.0       2018-04-26           2018-04   
...              ...  ...    ...       ...              ...               ...   
1143184         5421   83      F   50000.0       2016-03-07           2016-03   
1143185         5421   83      F   50000.0       2016-03-07           2016-03   
1143186         5421   83      F   50000.0       2016-03-07           2016-03   
1143187         5421   83      F   50000.0       2016-03-07           2016-03   
1143188         5421   83      F   50000.0       2016-03-07           2016-03   
1143189         5421   83      F   50000.0       2016-03-07           2016-03   
1143190         5421   83      F   50000.0       2016-03-07           2016-03   
1143191         5421   83      F   50000.0       2016-03-07           2016-03   
1143192         5421   83      F   50000.0       2016-03-07           2016-03   
1143193         5421   83      F   50000.0       2016-03-07           2016-03   
1143194         5421   83      F   50000.0       2016-03-07           2016-03   
1143195         5421   83      F   50000.0       2016-03-07           2016-03   
1143196         5421   83      F   50000.0       2016-03-07           2016-03   
1143197         5421   83      F   50000.0       2016-03-07           2016-03   
1143198         5421   83      F   50000.0       2016-03-07           2016-03   
1143199         5421   83      F   50000.0       2016-03-07           2016-03   
1143200         5421   83      F   50000.0       2016-03-07           2016-03   
1143201         5421   83      F   50000

In [12]:
# making sure the dataset contains only the transactions that appear before the end of an offer

full_data = full_data[full_data['time_of_transaction(hours)'] <= full_data['duration(hours)']]
full_data

customer_id  age gender    income membership_start membership_period  \
0                  1   55      F  112000.0       2017-07-15           2017-07   
1                  1   55      F  112000.0       2017-07-15           2017-07   
2                  1   55      F  112000.0       2017-07-15           2017-07   
3                  1   55      F  112000.0       2017-07-15           2017-07   
6                  2   75      F  100000.0       2017-05-09           2017-05   
7                  2   75      F  100000.0       2017-05-09           2017-05   
8                  2   75      F  100000.0       2017-05-09           2017-05   
9                  2   75      F  100000.0       2017-05-09           2017-05   
10                 2   75      F  100000.0       2017-05-09           2017-05   
11                 2   75      F  100000.0       2017-05-09           2017-05   
36                 4   65      M   53000.0       2018-02-09           2018-02   
37                 4   65      M   53000.0       2018-02-09           2018-02   
38                 4   65      M   53000.0       2018-02-09           2018-02   
39                 4   65      M   53000.0       2018-02-09           2018-02   
40                 4   65      M   53000.0       2018-02-09           2018-02   
51                 5   57      M   42000.0       2017-12-31           2017-12   
52                 5   57      M   42000.0       2017-12-31           2017-12   
53                 5   57      M   42000.0       2017-12-31           2017-12   
69                 6   61      F   40000.0       2018-05-01           2018-05   
76                 7   56      F   88000.0       2018-04-28           2018-04   
77                 7   56      F   88000.0       2018-04-28           2018-04   
78                 7   56      F   88000.0       2018-04-28           2018-04   
79                 7   56      F   88000.0       2018-04-28           2018-04   
97                 9   59      M   41000.0       2015-01-21           2015-01   
98                 9   59      M   41000.0       2015-01-21           2015-01   
99                 9   59      M   41000.0       2015-01-21           2015-01   
136               10   53      O   52000.0       2017-09-16           2017-09   
141               11   96      F   89000.0       2017-11-17           2017-11   
142               11   96      F   89000.0       2017-11-17           2017-11   
149               12   40      M   33000.0       2016-07-09           2016-07   
...              ...  ...    ...       ...              ...               ...   
1142904        11282   37      M   60000.0       2017-01-24           2017-01   
1142947         5401   77      F   71000.0       2017-04-25           2017-04   
1142948         5401   77      F   71000.0       2017-04-25           2017-04   
1142949         5401   77      F   71000.0       2017-04-25           2017-04   
1142989         5402   71      F   64000.0       2018-01-10           2018-01   
1142990         5402   71      F   64000.0       2018-01-10           2018-01   
1143011         9048   65      F   35000.0       2017-07-05           2017-07   
1143012         9048   65      F   35000.0       2017-07-05           2017-07   
1143047        12714   25      M   45000.0       2015-10-20           2015-10   
1143048        12714   25      M   45000.0       2015-10-20           2015-10   
1143065         9050   57      F   55000.0       2018-05-24           2018-05   
1143066         9050   57      F   55000.0       2018-05-24           2018-05   
1143077         5410   52      F   75000.0       2018-05-22           2018-05   
1143078         5410   52      F   75000.0       2018-05-22           2018-05   
1143079         5410   52      F   75000.0       2018-05-22           2018-05   
1143089        14309   39      F   54000.0       2016-09-21           2016-09   
1143090        14309   39      F   54000.0       2016-09-21           2016-09   
1143091        14309   39      F   54000

In [13]:
print(f"The number of transactions in the full data: {full_data.shape[0]}")
print(f"The number of variables: {full_data.shape[1]}")

The number of transactions in the full data: 238356
The number of variables: 25


As mentioned eariler, our goal is to have a dataset that contains only viewed and completed offers where transactions made by anu customers took a place before the end of the duration of an offer. That is, the above code assure that transactions made after the end of an offer are not included in the final, clean data.

In [14]:
# showing the number of transactions by offer_type for the final and clean data

full_data['offer_type'].value_counts()

discount    139360
bogo         98996
Name: offer_type, dtype: int64

We talked about the popularity of the 10 offers we have, and we found that two discount offers were the most popular. Here, we can see than most transactions were made for discount offers. 

In [15]:
# functions to return the individual datasets with respect to each column in the full_data

def full_dataset(df, column, ev):
    data = df[df[column] == ev]
    
    return data

def offer_dataset(df, offer_num):
    offer_num = full_dataset(df, 'offer_id', offer_num)
    
    return offer_num


#### <font color=blue> 2.2.1 Events

In [16]:
# creating datasets of each event for further analysis

df_received = full_dataset(full_data, 'event', 'offer received')
df_viewed = full_dataset(full_data, 'event', 'offer viewed')
df_completed = full_dataset(full_data, 'event', 'offer completed')

In [17]:
print(f"The number of received offers: {df_received.shape[0]}")

df_received.sample(3)

The number of received offers: 96626


customer_id  age gender   income membership_start membership_period  \
686193          8175   84      F  64000.0       2016-10-24           2016-10   
1122175         4661   40      M  63000.0       2015-11-09           2015-11   
648439         13210   34      M  42000.0       2017-12-18           2017-12   

         transaction_amount  time_of_transaction(hours)           event  \
686193                 6.93                         138  offer received   
1122175                1.65                          12  offer received   
648439                 2.83                         102  offer received   

         offer_id  ...  offer_completion(%)  completed(not_viewed)  \
686193          5  ...            75.210463                  -1404   
1122175         8  ...            50.204763                  -3019   
648439          5  ...            75.210463                  -1404   

         offer_type  difficulty($)  duration(hours)  reward  email mobile  \
686193     discount             10              240       2      1      1   
1122175        bogo             10              120      10      1      1   
648439     discount             10              240       2      1      1   

         social  web  
686193        1    1  
1122175       1    1  
648439        1    1  

[3 rows x 25 columns]

In [18]:
# overview of the transaction where the customers did view an offer

print(f"The number of viewed offers: {df_viewed.shape[0]}")

df_viewed

The number of viewed offers: 73103


customer_id  age gender    income membership_start membership_period  \
7                  2   75      F  100000.0       2017-05-09           2017-05   
10                 2   75      F  100000.0       2017-05-09           2017-05   
37                 4   65      M   53000.0       2018-02-09           2018-02   
39                 4   65      M   53000.0       2018-02-09           2018-02   
77                 7   56      F   88000.0       2018-04-28           2018-04   
79                 7   56      F   88000.0       2018-04-28           2018-04   
99                 9   59      M   41000.0       2015-01-21           2015-01   
151               12   40      M   33000.0       2016-07-09           2016-07   
156               12   40      M   33000.0       2016-07-09           2016-07   
161               12   40      M   33000.0       2016-07-09           2016-07   
166               12   40      M   33000.0       2016-07-09           2016-07   
171               12   40      M   33000.0       2016-07-09           2016-07   
176               12   40      M   33000.0       2016-07-09           2016-07   
220               13   69      F   57000.0       2016-08-14           2016-08   
223               13   69      F   57000.0       2016-08-14           2016-08   
226               13   69      F   57000.0       2016-08-14           2016-08   
229               13   69      F   57000.0       2016-08-14           2016-08   
232               13   69      F   57000.0       2016-08-14           2016-08   
235               13   69      F   57000.0       2016-08-14           2016-08   
238               13   69      F   57000.0       2016-08-14           2016-08   
241               13   69      F   57000.0       2016-08-14           2016-08   
304               14   45      M   33000.0       2018-07-07           2018-07   
329               15   61      M   98000.0       2017-11-21           2017-11   
409               19   79      F   48000.0       2015-04-15           2015-04   
411               19   79      F   48000.0       2015-04-15           2015-04   
413               19   79      F   48000.0       2015-04-15           2015-04   
415               19   79      F   48000.0       2015-04-15           2015-04   
417               19   79      F   48000.0       2015-04-15           2015-04   
507               22   75      M   52000.0       2015-11-29           2015-11   
510               22   75      M   52000.0       2015-11-29           2015-11   
...              ...  ...    ...       ...              ...               ...   
1142261         9027   61      M   41000.0       2016-04-20           2016-04   
1142265         9027   61      M   41000.0       2016-04-20           2016-04   
1142423        12710   26      M   49000.0       2013-11-23           2013-11   
1142425        12710   26      M   49000.0       2013-11-23           2013-11   
1142500         5376   39      M   33000.0       2018-02-17           2018-02   
1142503         5376   39      M   33000.0       2018-02-17           2018-02   
1142589         5379   33      M   57000.0       2018-02-13           2018-02   
1142601        11275   73      F   98000.0       2017-08-08           2017-08   
1142616         5381   59      F   45000.0       2017-06-10           2017-06   
1142729         5391   43      M   58000.0       2014-10-27           2014-10   
1142731         5391   43      M   58000.0       2014-10-27           2014-10   
1142733         5391   43      M   58000.0       2014-10-27           2014-10   
1142769         5392   18      F   31000.0       2015-12-19           2015-12   
1142771         5392   18      F   31000.0       2015-12-19           2015-12   
1142773         5392   18      F   31000.0       2015-12-19           2015-12   
1142775         5392   18      F   31000.0       2015-12-19           2015-12   
1142890        11281   19      M   53000.0       2017-09-06           2017-09   
1142900        11282   37      M   60000

In [19]:
# overview of the transaction where the customers did complete an offer

print(f"The number of completed offers: {df_completed.shape[0]}")

df_completed

The number of completed offers: 68627


customer_id  age gender    income membership_start membership_period  \
1                  1   55      F  112000.0       2017-07-15           2017-07   
3                  1   55      F  112000.0       2017-07-15           2017-07   
8                  2   75      F  100000.0       2017-05-09           2017-05   
11                 2   75      F  100000.0       2017-05-09           2017-05   
40                 4   65      M   53000.0       2018-02-09           2018-02   
53                 5   57      M   42000.0       2017-12-31           2017-12   
142               11   96      F   89000.0       2017-11-17           2017-11   
150               12   40      M   33000.0       2016-07-09           2016-07   
155               12   40      M   33000.0       2016-07-09           2016-07   
160               12   40      M   33000.0       2016-07-09           2016-07   
165               12   40      M   33000.0       2016-07-09           2016-07   
170               12   40      M   33000.0       2016-07-09           2016-07   
175               12   40      M   33000.0       2016-07-09           2016-07   
221               13   69      F   57000.0       2016-08-14           2016-08   
224               13   69      F   57000.0       2016-08-14           2016-08   
227               13   69      F   57000.0       2016-08-14           2016-08   
230               13   69      F   57000.0       2016-08-14           2016-08   
233               13   69      F   57000.0       2016-08-14           2016-08   
236               13   69      F   57000.0       2016-08-14           2016-08   
239               13   69      F   57000.0       2016-08-14           2016-08   
242               13   69      F   57000.0       2016-08-14           2016-08   
305               14   45      M   33000.0       2018-07-07           2018-07   
328               15   61      M   98000.0       2017-11-21           2017-11   
373               18   41      F   41000.0       2015-09-21           2015-09   
506               22   75      M   52000.0       2015-11-29           2015-11   
509               22   75      M   52000.0       2015-11-29           2015-11   
541               24   53      F  117000.0       2016-12-31           2016-12   
571               25   49      F   57000.0       2017-04-08           2017-04   
574               25   49      F   57000.0       2017-04-08           2017-04   
577               25   49      F   57000.0       2017-04-08           2017-04   
...              ...  ...    ...       ...              ...               ...   
1141768        13575   66      F   73000.0       2016-02-01           2016-02   
1141795         9015   80      F   75000.0       2017-12-09           2017-12   
1141798         9015   80      F   75000.0       2017-12-09           2017-12   
1141848        12704   57      M   75000.0       2018-02-05           2018-02   
1141931         9016   66      M   84000.0       2016-10-20           2016-10   
1141934         9016   66      M   84000.0       2016-10-20           2016-10   
1141937         9016   66      M   84000.0       2016-10-20           2016-10   
1141940         9016   66      M   84000.0       2016-10-20           2016-10   
1141943         9016   66      M   84000.0       2016-10-20           2016-10   
1142109         5364   86      F   44000.0       2016-11-10           2016-11   
1142112         5364   86      F   44000.0       2016-11-10           2016-11   
1142145         9024   52      F   97000.0       2016-08-20           2016-08   
1142160         9026   57      F   53000.0       2016-12-26           2016-12   
1142163         9026   57      F   53000.0       2016-12-26           2016-12   
1142166         9026   57      F   53000.0       2016-12-26           2016-12   
1142226        12706   24      M   48000.0       2017-02-01           2017-02   
1142262         9027   61      M   41000.0       2016-04-20           2016-04   
1142264         9027   61      M   41000

After writting some functions that return the full data with respect to a specific variable, we will look next to top_customers customers who completed any offer and paid the most amount.

In [20]:
# making sure we have only unique_customers even if the customer made transaction more than once for an offer
unique_customers = df_completed.drop_duplicates(subset=['customer_id', 'time_of_transaction(hours)', 'offer_id'], keep='first')

# finding the top customers based on the sum of their transaction_amount of all offers completed 

top_customers = unique_customers.groupby('customer_id')['transaction_amount'].sum().sort_values(ascending=False).head(10)
top_customers

customer_id
8658     5056.42
4307     3343.89
12886    3127.56
2896     3030.39
6759     2955.24
10196    2870.32
11936    2857.77
6307     2833.60
1828     2608.13
10487    2427.42
Name: transaction_amount, dtype: float64

It looks like some customers paid thousands of dollars for Starbucks. Next, we will see the total amount of money made for each offer.

In [21]:
# finding the top offers based on the sum of the transaction_amount made by all customers who completed the offer

top_offers = unique_customers.groupby('offer_id')['transaction_amount'].sum().sort_values(ascending=False).head(10)
top_offers

offer_id
5    194632.34
7    149296.90
6    122381.83
2    110113.80
1    107063.15
4    106886.66
3     84649.89
8     77249.56
Name: transaction_amount, dtype: float64

Offers 5 and 7 have the most sum of transactions amount made by all customers.

In [22]:
# finding the average transaction_amount over all transactions and offer where customers completed the offers

df_completed['transaction_amount'].mean()

16.55074431346271

In [23]:
# creating a dataframe grouped by the time when each transaction takes a place from the start of an offer
# showing a description of the amount spent by that time

transcation_by_time = df_completed.groupby('time_of_transaction(hours)').describe()['transaction_amount'].reset_index()
transcation_by_time = transcation_by_time.drop(['std', '25%', '75%'], axis=1)
transcation_by_time

time_of_transaction(hours)   count       mean   min     50%      max
0                            0  1421.0  15.365721  0.05  14.070   195.24
1                            6  1854.0  16.203981  0.07  14.440   448.97
2                           12  1972.0  21.033210  0.06  15.860   871.51
3                           18  2127.0  20.125129  0.05  14.040   962.10
4                           24  2219.0  15.679117  0.07  13.950   674.48
5                           30  2430.0  15.904683  0.05  13.600   575.23
6                           36  2353.0  17.465168  0.05  14.160   947.43
7                           42  2485.0  16.747191  0.05  13.470   657.26
8                           48  2473.0  16.036284  0.09  14.150   475.20
9                           54  2391.0  16.191409  0.08  14.100   845.01
10                          60  2377.0  17.972659  0.07  14.280   713.20
11                          66  2522.0  14.652895  0.05  14.170    92.52
12                          72  2413.0  14.825843  0.08  14.260   115.31
13                          78  2374.0  14.107982  0.05  13.220   105.24
14                          84  2436.0  16.903555  0.08  13.720   529.00
15                          90  2323.0  17.196621  0.14  13.530   841.06
16                          96  2370.0  16.927481  0.05  14.345   565.22
17                         102  2260.0  19.470159  0.05  14.160  1001.85
18                         108  2072.0  16.235188  0.06  13.420   936.94
19                         114  2141.0  15.340869  0.09  14.810   284.86
20                         120  2320.0  15.941483  0.05  14.560   337.09
21                         126  1574.0  15.293977  0.06  14.200   345.50
22                         132  1550.0  16.306477  0.08  14.060   918.02
23                         138  1480.0  20.933142  0.12  13.105   738.81
24                         144  1537.0  15.119727  0.07  14.310   314.75
25                         150  1420.0  15.421669  0.06  13.195   791.79
26                         156  1501.0  15.996196  0.14  13.730   367.37
27                         162  1540.0  15.368357  0.18  13.560   370.10
28                         168  1801.0  15.461855  0.09  13.540   881.35
29                         174   585.0  15.149573  0.12  12.690   562.54
30                         180   742.0  17.571604  0.21  13.740   841.45
31                         186   747.0  16.151914  0.06  13.820   747.74
32                         192   712.0  15.604157  0.21  14.185   253.81
33                         198   734.0  17.097439  0.06  14.710   588.64
34                         204   772.0  15.846269  0.05  14.150   240.32
35                         210   802.0  19.320786  0.05  13.615   718.86
36                         216   814.0  16.168428  0.05  13.765   762.70
37                         222   790.0  15.203380  0.05  14.145   295.89
38                         228   768.0  18.318034  0.05  13.945   831.65
39                         234   704.0  14.537585  0.07  12.490   420.13
40                         240   721.0  16.181678  0.10  14.830   601.64

In [24]:
# a function to split the data by column and then returns a description of the all transcations grouped by their time

def transcation_by_time(df, col, target):
    transcations = df[df[col] == target]
    transcations = transcations.groupby('time_of_transaction(hours)').describe()['transaction_amount'].reset_index()
    transcations = transcations.drop(['std', '25%', '75%'], axis=1)
    return transcations

In [25]:
# plotting a trend that shows the average Amount Spent since a Start of an Offer at a specific time

f_transcations = transcation_by_time(df_completed, 'gender', 'F')
m_transcations = transcation_by_time(df_completed, 'gender', 'M')

trace_mean1 = go.Scatter(
    x=f_transcations['time_of_transaction(hours)'],
    y=f_transcations['mean'],
    name = "Female",
    line = dict(color = 'pink'),
    opacity = 0.6)

trace_mean2 = go.Scatter(
    x=m_transcations['time_of_transaction(hours)'],
    y=m_transcations['mean'],
    name = "Male",
    line = dict(color = 'cornflowerblue'),
    opacity = 0.6)

data1 = [trace_mean1, trace_mean2]

layout = {
    'title': 'Average Amount Spent Since a Start of an Offer Trend',
    'xaxis': {'title': 'Time Since a Start of an Offer (hours)'},
    'yaxis': {'title': 'Average Amount ($)', 
              "range": [
                10,
                30
            ]},
               
    'shapes': [
        # Line Horizontal, average
        {
            'type': 'line',
            'x0': 0,
            'y0': 16.55,
            'x1': 243,
            'y1': 16.55,
            'line': {
                'color': 'black',
                'width': 1,
                'dash': 'dashdot',
            }
        },
        
        # 1st highlight above average amount
        {
            'type': 'rect',
            # x-reference is assigned to the x-values
            'xref': 'paper',
            # y-reference is assigned to the plot [0,1]
            'yref': 'y',
            'x0': 0,
            'y0': 16.55,
            'x1': 1,
            'y1': 30,
            'fillcolor': 'olive',
            'opacity': 0.1,
            'line': {
                'width': 0,
            }
        },
        
        # 3nd highlight below average months
        {
            'type': 'rect',
            'xref': 'paper',
            'yref': 'y',
            'x0': 0,
            'y0': 16.55,
            'x1': 1,
            'y1': 0,
            'fillcolor': 'tomato',
            'opacity': 0.1,
            'line': {
                'width': 0,
            }
        }
    ]
}

layout.update(dict(annotations=[go.Annotation(text="Overall Average Amount ($16.55) Spent After the Start of an Offer", 
                                              x=150, 
                                              y=16.55,
                                              ax=10, 
                                              ay=-120)]))
        
fig = dict(data=data1, layout=layout)
py.iplot(fig, filename = "Amount Spent since a Start of an Offer Trend")

/Users/Saleh/anaconda3/lib/python3.7/site-packages/plotly/graph_objs/_deprecations.py:144: DeprecationWarning:

plotly.graph_objs.Annotation is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.layout.Annotation
  - plotly.graph_objs.layout.scene.Annotation


/Users/Saleh/anaconda3/lib/python3.7/site-packages/IPython/core/display.py:689: UserWarning:

Consider using IPython.display.IFrame instead



The trend of the transactions made since a start of an offer shows that, on average, female customers paid more than male customers did at any time from the beginning of an offer up to 10 days. Back to our concern in the first chart; even though the number of male customers is higher, female customers paid more than male customers have paid. The only exception is transactions made after 228 hours from the start of an offer. On average, all customers paid an overall amount of $16.55 at any time since an offer has started. We can see female customers paid more than the average at any time! Whereas male customers most the time paid less than the average. Also, we can observe some peaks over time for both gender where they, on average, paid more than usual. That could be during the weekends or specific times during the day.


#### <font color=blue> 2.2.2 Offer Type

In [26]:
# creating datasets of each offer_type for further analysis

df_bogo = full_dataset(full_data, 'offer_type', 'bogo')
df_discount = full_dataset(full_data, 'offer_type', 'discount')

In [27]:
# overview of the transaction where the offer is BOGO

df_bogo.sample(3)

customer_id  age gender    income membership_start membership_period  \
33058           1432   74      F  102000.0       2016-02-26           2016-02   
1063041        11885   26      M   63000.0       2016-06-09           2016-06   
1053085         9892   38      M   44000.0       2015-09-17           2015-09   

         transaction_amount  time_of_transaction(hours)            event  \
33058                 23.36                         162  offer completed   
1063041               12.33                           6   offer received   
1053085                5.63                          30   offer received   

         offer_id  ...  offer_completion(%)  completed(not_viewed)  \
33058           1  ...            62.647719                    689   
1063041         8  ...            50.204763                  -3019   
1053085         8  ...            50.204763                  -3019   

         offer_type  difficulty($)  duration(hours)  reward  email mobile  \
33058          bogo              5              168       5      1      1   
1063041        bogo             10              120      10      1      1   
1053085        bogo             10              120      10      1      1   

         social  web  
33058         0    1  
1063041       1    1  
1053085       1    1  

[3 rows x 25 columns]

In [28]:
df_discount.sample(3)

customer_id  age gender   income membership_start membership_period  \
860656         4328   22      M  32000.0       2015-12-24           2015-12   
746562          658   67      M  42000.0       2017-10-27           2017-10   
802155        11895   58      M  93000.0       2016-07-29           2016-07   

        transaction_amount  time_of_transaction(hours)           event  \
860656                1.63                         120    offer viewed   
746562                0.50                          66  offer received   
802155               19.79                          18    offer viewed   

        offer_id  ...  offer_completion(%)  completed(not_viewed)  offer_type  \
860656         6  ...            73.418482                  -1493    discount   
746562         6  ...            73.418482                  -1493    discount   
802155         6  ...            73.418482                  -1493    discount   

        difficulty($)  duration(hours)  reward  email mobile  social  web  
860656              7              168       3      1      1       1    1  
746562              7              168       3      1      1       1    1  
802155              7              168       3      1      1       1    1  

[3 rows x 25 columns]

In [29]:
# function to return top customers or offers for a specific offer type
# based on the sum of their transaction_amount of all offers completed 

def tops(df, col):
    # making sure we have only unique_customers who completed an offer even if the customer made transaction more than once for that offer
    completed_offers = df[df['event'] == 'offer completed']
    unique_customers = completed_offers.drop_duplicates(subset=['customer_id', 'time_of_transaction(hours)', 'offer_id'], keep='first')

    # finding the tops based on the sum of their transaction_amount of all offers completed for that specific offer type 

    top1 = unique_customers.groupby(col)['transaction_amount'].sum().sort_values(ascending=False).head(10)
    
    return top1

def tops_by_gender(df):
    # making sure we have only unique_customers who completed an offer even if the customer made transaction more than once for that offer
    completed_offers = df[df['event'] == 'offer completed']
    unique_customers = completed_offers.drop_duplicates(subset=['customer_id', 'time_of_transaction(hours)', 'offer_id'], keep='first')

    # finding the amount of all completed offer by gender

    amount = unique_customers.groupby(['offer_id', 'gender'])['transaction_amount'].sum()
    
    return amount

def customer_report(cid, df=df_discount):
    report = df[df.event == 'offer completed']
    report = report[report.customer_id == cid]
    
    return report

In [30]:
# finding the top customers based on the sum of their transaction_amount of all BOGO offers completed 

tops(df_bogo, 'customer_id')

customer_id
4307     1990.88
1828     1724.50
261      1573.74
10822    1515.80
2896     1507.78
621      1465.94
6307     1416.80
10080    1408.48
6624     1301.02
10487    1184.38
Name: transaction_amount, dtype: float64

As we now focus on transactions made for only the BOGO offers, we can see the top 10 customers who paid the most for all BOGO offers

In [31]:
# finding the top customers based on the sum of their transaction_amount of all discount offers completed 

tops(df_discount, 'customer_id')

customer_id
8658     4057.18
12886    3127.56
6759     2216.43
9904     2049.56
12108    2019.64
10196    1933.38
11936    1928.68
10048    1853.52
11791    1765.39
7923     1740.66
Name: transaction_amount, dtype: float64

Here, we find the top 10 customers with respect to the discount offers.

In [32]:
# reporting more info about a customer

customer_report(8658, df_discount)

customer_id  age gender    income membership_start membership_period  \
537915         8658   60      M  106000.0       2016-07-02           2016-07   
537918         8658   60      M  106000.0       2016-07-02           2016-07   
537921         8658   60      M  106000.0       2016-07-02           2016-07   
707286         8658   60      M  106000.0       2016-07-02           2016-07   
707289         8658   60      M  106000.0       2016-07-02           2016-07   
707292         8658   60      M  106000.0       2016-07-02           2016-07   
707295         8658   60      M  106000.0       2016-07-02           2016-07   
877717         8658   60      M  106000.0       2016-07-02           2016-07   
877720         8658   60      M  106000.0       2016-07-02           2016-07   
877723         8658   60      M  106000.0       2016-07-02           2016-07   
987953         8658   60      M  106000.0       2016-07-02           2016-07   
987955         8658   60      M  106000.0       2016-07-02           2016-07   
987957         8658   60      M  106000.0       2016-07-02           2016-07   
987959         8658   60      M  106000.0       2016-07-02           2016-07   

        transaction_amount  time_of_transaction(hours)            event  \
537915               24.23                          30  offer completed   
537918              947.43                          36  offer completed   
537921               27.58                         120  offer completed   
707286               24.23                          30  offer completed   
707289              947.43                          36  offer completed   
707292               27.58                         120  offer completed   
707295               30.11                         180  offer completed   
877717               24.23                          30  offer completed   
877720              947.43                          36  offer completed   
877723               27.58                         120  offer completed   
987953               24.23                          30  offer completed   
987955              947.43                          36  offer completed   
987957               27.58                         120  offer completed   
987959               30.11                         180  offer completed   

        offer_id  ...  offer_completion(%)  completed(not_viewed)  offer_type  \
537915         4  ...            58.980546                    451    discount   
537918         4  ...            58.980546                    451    discount   
537921         4  ...            58.980546                    451    discount   
707286         5  ...            75.210463                  -1404    discount   
707289         5  ...            75.210463                  -1404    discount   
707292         5  ...            75.210463                  -1404    discount   
707295         5  ...            75.210463                  -1404    discount   
877717         6  ...            73.418482                  -1493    discount   
877720         6  ...            73.418482                  -1493    discount   
877723         6  ...            73.418482                  -1493    discount   
987953         7  ...            50.341957                   1171    discount   
987955         7  ...            50.341957                   1171    discount   
987957         7  ...            50.341957                   1171    discount   
987959         7  ...            50.341957                   1171    discount   

        difficulty($)  duration(hours)  reward  email mobile  social  web  
537915             10              168       2      1      1       0    1  
537918             10              168       2      1      1       0    1  
537921             10              168       2      1      1       0    1  
707286             10              240       2      1      1       1    1  
707289             10              240       2      1      1       1    1  
707292   

In [33]:
# finding the top offers based on the sum of the transaction_amount made by all customers who completed the offer

tops(df_bogo, 'offer_id')

offer_id
2    110113.80
1    107063.15
3     84649.89
8     77249.56
Name: transaction_amount, dtype: float64

As mentioned eariler, we have 4 BOGO offers and 4 Discount offers. Here we see that offer 2 had the most total transactions amount over the other BOGO offers.

In [34]:
# finding the top offers based on the sum of the transaction_amount made by all customers who completed the offer

tops(df_discount, 'offer_id')

offer_id
5    194632.34
7    149296.90
6    122381.83
4    106886.66
Name: transaction_amount, dtype: float64

Offer 5 made the most among other Discount offers, and overall!

In [35]:
# finding the total amount for each BOGO offer by gender 

tops_by_gender(df_bogo)

offer_id  gender
1         F         55421.53
          M         49555.68
          O          2085.94
2         F         56392.20
          M         51419.22
          O          2302.38
3         F         43190.65
          M         40197.47
          O          1261.77
8         F         42923.16
          M         33526.68
          O           799.72
Name: transaction_amount, dtype: float64

More details about the total transactions amount made for each BOGO offer by customers with respect to their gender. Overall, female customers paid more than male customers. Both, Female and male customers paid most for offer 2.

In [36]:
# finding the total amount for each discount offer by gender 

tops_by_gender(df_discount)

offer_id  gender
4         F         56113.92
          M         48823.54
          O          1949.20
5         F         98573.24
          M         93458.66
          O          2600.44
6         F         63224.15
          M         57367.13
          O          1790.55
7         F         76970.11
          M         69990.11
          O          2336.68
Name: transaction_amount, dtype: float64

With respect to Discount offers, again, femal customers paid more than male customers. Both paid the most for offer 5.


#### <font color=blue> 2.2.3 Gender

In [37]:
# creating datasets for each gender for further analysis

df_male = full_dataset(full_data, 'gender', 'M')
df_female = full_dataset(full_data, 'gender', 'F')
df_other = full_dataset(full_data, 'gender', 'O')

In [38]:
# overview of the transactions made by male customers
df_male.sample(3)

customer_id  age gender   income membership_start membership_period  \
1016520          614   31      M  39000.0       2017-09-02           2017-09   
793610          9954   53      M  75000.0       2016-02-16           2016-02   
20940            903   54      M  56000.0       2017-06-26           2017-06   

         transaction_amount  time_of_transaction(hours)         event  \
1016520                7.05                          60  offer viewed   
793610                13.01                         162  offer viewed   
20940                 16.76                          60  offer viewed   

         offer_id  ...  offer_completion(%)  completed(not_viewed)  \
1016520         8  ...            50.204763                  -3019   
793610          6  ...            73.418482                  -1493   
20940           1  ...            62.647719                    689   

         offer_type  difficulty($)  duration(hours)  reward  email mobile  \
1016520        bogo             10              120      10      1      1   
793610     discount              7              168       3      1      1   
20940          bogo              5              168       5      1      1   

         social  web  
1016520       1    1  
793610        1    1  
20940         0    1  

[3 rows x 25 columns]

In [39]:
# overview of the transactions made by female customers

df_female.sample(3)

customer_id  age gender   income membership_start membership_period  \
53765          2292   65      F  85000.0       2015-08-02           2015-08   
876785        11065   28      F  57000.0       2017-10-16           2017-10   
206106         2942   26      F  69000.0       2015-10-30           2015-10   

        transaction_amount  time_of_transaction(hours)            event  \
53765                18.65                         150   offer received   
876785                8.70                          24  offer completed   
206106               25.77                          66  offer completed   

        offer_id  ...  offer_completion(%)  completed(not_viewed)  offer_type  \
53765          1  ...            62.647719                    689        bogo   
876785         6  ...            73.418482                  -1493    discount   
206106         2  ...            54.720934                  -2244        bogo   

        difficulty($)  duration(hours)  reward  email mobile  social  web  
53765               5              168       5      1      1       0    1  
876785              7              168       3      1      1       1    1  
206106             10              168      10      1      1       1    0  

[3 rows x 25 columns]

In [40]:
# finding the top male customers based on the sum of their transaction_amount

tops(df_male, 'customer_id')

customer_id
8658     5056.42
4307     3343.89
6307     2833.60
261      2360.61
10048    2316.90
10822    2273.70
8260     2107.81
7862     2030.46
8976     1751.50
7923     1740.66
Name: transaction_amount, dtype: float64

Eariler, we looked at the overall top customers. Here, we find the top 10 male customers based on the total amount they paid for all offer.

In [41]:
# finding the top female customers based on the sum of their transaction_amount

tops(df_female, 'customer_id')

customer_id
12886    3127.56
2896     3030.39
6759     2955.24
10196    2870.32
11936    2857.77
1828     2608.13
10487    2427.42
11791    2344.68
3342     2166.70
9904     2124.15
Name: transaction_amount, dtype: float64

The top 10 female customers.

In [42]:
# reporting more info about a customer

customer_report(9904, df_female)

customer_id  age gender   income membership_start membership_period  \
332417         9904   58      F  64000.0       2015-11-16           2015-11   
332420         9904   58      F  64000.0       2015-11-16           2015-11   
332423         9904   58      F  64000.0       2015-11-16           2015-11   
332426         9904   58      F  64000.0       2015-11-16           2015-11   
615311         9904   58      F  64000.0       2015-11-16           2015-11   
615314         9904   58      F  64000.0       2015-11-16           2015-11   
615317         9904   58      F  64000.0       2015-11-16           2015-11   
615320         9904   58      F  64000.0       2015-11-16           2015-11   
615323         9904   58      F  64000.0       2015-11-16           2015-11   
615326         9904   58      F  64000.0       2015-11-16           2015-11   
615329         9904   58      F  64000.0       2015-11-16           2015-11   
615332         9904   58      F  64000.0       2015-11-16           2015-11   
789347         9904   58      F  64000.0       2015-11-16           2015-11   
789350         9904   58      F  64000.0       2015-11-16           2015-11   
789353         9904   58      F  64000.0       2015-11-16           2015-11   
789356         9904   58      F  64000.0       2015-11-16           2015-11   
789359         9904   58      F  64000.0       2015-11-16           2015-11   
789362         9904   58      F  64000.0       2015-11-16           2015-11   
789365         9904   58      F  64000.0       2015-11-16           2015-11   
933514         9904   58      F  64000.0       2015-11-16           2015-11   
933517         9904   58      F  64000.0       2015-11-16           2015-11   
933520         9904   58      F  64000.0       2015-11-16           2015-11   
933523         9904   58      F  64000.0       2015-11-16           2015-11   
933526         9904   58      F  64000.0       2015-11-16           2015-11   
933529         9904   58      F  64000.0       2015-11-16           2015-11   
933532         9904   58      F  64000.0       2015-11-16           2015-11   
933535         9904   58      F  64000.0       2015-11-16           2015-11   

        transaction_amount  time_of_transaction(hours)            event  \
332417               14.43                           6  offer completed   
332420               25.08                          30  offer completed   
332423               21.71                          48  offer completed   
332426               13.37                         108  offer completed   
615311               14.43                           6  offer completed   
615314               25.08                          30  offer completed   
615317               21.71                          48  offer completed   
615320               13.37                         108  offer completed   
615323               11.20                         132  offer completed   
615326              570.78                         138  offer completed   
615329               13.43                         156  offer completed   
615332               19.78                         204  offer completed   
789347               14.43                           6  offer completed   
789350               25.08                          30  offer completed   
789353               21.71                          48  offer completed   
789356               13.37                         108  offer completed   
789359               11.20                         132  offer completed   
789362              570.78                         138  offer completed   
789365               13.43                         156  offer completed   
933514               14.43                           6  offer completed   
933517               25.08                          30  offer completed   
933520               21.71                          48  offer completed   
933523               13.37                         108  offer complete

In [43]:
# finding the top offers based on the sum of the transaction_amount made by male customers who completed that offer

tops(df_male, 'offer_id')

offer_id
5    93458.66
7    69990.11
6    57367.13
2    51419.22
1    49555.68
4    48823.54
3    40197.47
8    33526.68
Name: transaction_amount, dtype: float64

In [44]:
# finding the top offers based on the sum of the transaction_amount made by male customers who completed that offer

tops(df_female, 'offer_id')

offer_id
5    98573.24
7    76970.11
6    63224.15
2    56392.20
4    56113.92
1    55421.53
3    43190.65
8    42923.16
Name: transaction_amount, dtype: float64

In [45]:
# function to return plots with respect to different distributions by gender

def age_distributions(df, df2, color, color2):
    df = df.drop_duplicates(subset='customer_id', keep='first')
    df2 = df2.drop_duplicates(subset='customer_id', keep='first')
    x = df.age
    x2 = df2.age

    trace1 = go.Histogram(
        x=x,
        name='Female',
        opacity=0.6,
        nbinsx = 7,
        marker=dict(
            color=color)
    )
    
    trace2 = go.Histogram(
        x=x2,
        name='Male',
        opacity=0.6,
        nbinsx = 7,
        marker=dict(
            color=color2)
    )

    data1 = [trace1, trace2]
    layout = go.Layout(
        barmode='stack',
        bargap=0.1,
        title = 'Age by Gender',
        xaxis=dict(
            title='Age'),
        yaxis=dict(
            title='Total number of Customers'))
    
    updatemenus = list([
    dict(active=0,
         buttons=list([   
            dict(label = 'All',
                 method = 'update',
                 args = [{'visible': [True, True]},
                         {'title': 'Age Distribution by Gender'}]),
             dict(label = 'Female',
                 method = 'update',
                 args = [{'visible': [True, False]},
                         {'title': 'Age Distribution of Male Customers'}]),
            dict(label = 'Male',
                 method = 'update',
                 args = [{'visible': [False, True]},
                         {'title': 'Age Distribution of Female Customers'}])
            ]),
        )
    ])

    layout.update(dict(updatemenus=updatemenus))

    fig = go.Figure(data=data1, layout=layout)
    plot = py.iplot(fig, filename='Age by Gender')
    
    return plot

def income_distributions(df, df2, color, color2):
    df = df.drop_duplicates(subset='customer_id', keep='first')
    df2 = df2.drop_duplicates(subset='customer_id', keep='first')
    x = df.income
    x2 = df2.income

    trace1 = go.Histogram(
        x=x,
        name='Female',
        opacity=0.6,
        nbinsx = 7,
        marker=dict(
            color=color)
    )
    
    trace2 = go.Histogram(
        x=x2,
        name='Male',
        opacity=0.6,
        nbinsx = 7,
        marker=dict(
            color=color2)
    )

    data2 = [trace1, trace2]
    layout = go.Layout(
        barmode='stack',
        bargap=0.1,
        title = 'Income by Gender',
        xaxis=dict(
            title='Income'),
        yaxis=dict(
            title='Total number of Customers'))
    
        
    updatemenus = list([
    dict(active=0,
         buttons=list([
            
            dict(label = 'All',
                 method = 'update',
                 args = [{'visible': [True, True]},
                         {'title': 'Income Distribution by Gender'}]),

            dict(label = 'Female',
                 method = 'update',
                 args = [{'visible': [True, False]},
                         {'title': 'Income Distribution of Male Customers'}]),
            dict(label = 'Male',
                 method = 'update',
                 args = [{'visible': [False, True]},
                         {'title': 'Income Distribution of Female Customers'}])

            ]),
        )
    ])

    layout.update(dict(updatemenus=updatemenus))

    fig = go.Figure(data=data2, layout=layout)
    plot = py.iplot(fig, filename='Income by Gender')
    
    return plot

# function to return an analysis of the numbers and percentage of all transaction by each event

def analysis(df1, col1, col2, col3):
    v = df1[df1['event'] == 'offer viewed']
    v = v.drop_duplicates(subset=['customer_id', 'offer_id'], keep='first')

    c = df1[df1['event'] == 'offer completed']
    c = c.drop_duplicates(subset=['customer_id', 'offer_id'], keep='first')

    received = df1.drop_duplicates(subset=['customer_id', 'offer_id'], keep='first')

    viewed = pd.Series(v.offer_id).value_counts().reset_index().rename(columns={'index': 'offer_id_v', 'offer_id': 'viewed'})
    completed = pd.Series(c.offer_id).value_counts().reset_index().rename(columns={'index': 'offer_id_c', 'offer_id': 'completed'})
    received = pd.Series(received.offer_id).value_counts().reset_index().rename(columns={'index': 'offer_id_r', 'offer_id': 'received'})


    analysis = pd.concat([received, viewed, completed], axis=1).rename(columns={'offer_id_r': 'offer_id', 'viewed': col2, 'completed': col3, 'received': col1})
    analysis[col2+'(%)'] = round(analysis[col2]/analysis[col1]*100, 2)
    analysis[col3+'(%)'] = round(analysis[col3]/analysis[col1]*100, 2)

    analysis = analysis.drop(['offer_id_c', 'offer_id_v'], axis=1)
    
    return analysis

In [46]:
# plotting the age_distributions 

age_distributions(df_female, df_male, 'pink', 'cornflowerblue')

Another look at the age distribution by gender. The box plots confirm that the majority of the customers for both genders are between 40 and 60 years old.

In [49]:
# plotting the income_distributions 

income_distributions(df_female, df_male, 'pink', 'cornflowerblue')

Here, we confirm the previous findings of the income distributions. The plot confirms that most customers for all gender types make between 40k and 60k. Most of the female customers make between 60k and 80k while most male customers make between 40k and 60k a year.

In [50]:
# showing an analysis of each offer for both genders; male and female customers

overall_analysis = analysis(full_data, 'received', 'overall_views', 'overall_completion')
overall_analysis

offer_id  received  overall_views  overall_completion  overall_views(%)  \
0         5      4533           4402                3729             97.11   
1         7      4451           3711                3169             83.37   
2         2      3904           3552                2773             90.98   
3         6      3837           3276                2592             85.38   
4         1      3802           3248                2573             85.43   
5         4      3776           2175                2499             57.60   
6         3      3385           2132                2374             62.98   
7         8      3349           1607                1917             47.98   

   overall_completion(%)  
0                  82.26  
1                  71.20  
2                  71.03  
3                  67.55  
4                  67.67  
5                  66.18  
6                  70.13  
7                  57.24

In [51]:
# showing an analysis of each offer for male customers

male_analysis = analysis(df_male, 'received', 'male_views', 'male_completion')
male_analysis

offer_id  received  male_views  male_completion  male_views(%)  \
0         5      2639        2554             2052          96.78   
1         7      2554        2174             1755          85.12   
2         2      2275        2106             1441          92.57   
3         6      2250        1884             1354          83.73   
4         1      2194        1878             1324          85.60   
5         4      2166        1196             1265          55.22   
6         8      1944        1156             1143          59.47   
7         3      1941         861              917          44.36   

   male_completion(%)  
0               77.76  
1               68.72  
2               63.34  
3               60.18  
4               60.35  
5               58.40  
6               58.80  
7               47.24

In [52]:
# showing an analysis of each offer for female customers

female_analysis = analysis(df_female, 'received', 'female_views', 'female_completion')
female_analysis

offer_id  received  female_views  female_completion  female_views(%)  \
0         5      1836          1790               1626            97.49   
1         7      1835          1483               1371            80.82   
2         2      1569          1393               1281            88.78   
3         4      1556          1353               1261            86.95   
4         1      1541          1324               1197            85.92   
5         6      1531           934               1188            61.01   
6         3      1396           929               1134            66.55   
7         8      1365           711                970            52.09   

   female_completion(%)  
0                 88.56  
1                 74.71  
2                 81.64  
3                 81.04  
4                 77.68  
5                 77.60  
6                 81.23  
7                 71.06

In [53]:
# preparing a dataframe shows the completion percentages of each offer by gender

completion_perc = pd.merge(pd.merge(female_analysis, 
                                    male_analysis, on='offer_id'),
                           overall_analysis, on='offer_id')
col_list = ['offer_id', 'female_completion(%)', 'male_completion(%)', 'overall_completion(%)']
completion_perc = completion_perc[col_list].sort_values(by='offer_id').set_index('offer_id')

completion_perc

female_completion(%)  male_completion(%)  overall_completion(%)
offer_id                                                                 
1                        77.68               60.35                  67.67
2                        81.64               63.34                  71.03
3                        81.23               47.24                  70.13
4                        81.04               58.40                  66.18
5                        88.56               77.76                  82.26
6                        77.60               60.18                  67.55
7                        74.71               68.72                  71.20
8                        71.06               58.80                  57.24

After the data has been cleaned even further during the previous processes, here is a completion rate comparison of the genders for each offer. The overall completion rate account for customers, again, offer 5 is the most popular offer. Oviously, female customers reponse to offer more than male customers. The following chart illustrates the number where we can see a clear difference between female customers actions toward offers and the male customers response.

In [54]:
# plotting the Percentages of Completed offers by Gender

f_completed = completion_perc['female_completion(%)']
m_completed = completion_perc['male_completion(%)']
overall_completed = completion_perc['overall_completion(%)']
offers = completion_perc.index

x = offers
y = f_completed
y2 = m_completed
y3 = overall_completed

trace1 = go.Bar(
    x=x,
    y=y,
    name='Female',
    #hoverinfo = 'y',
    hovertemplate = '<i>Percentage of all Female Customers who completed the Offer</i>: %{y:.2f}%'
                    '<br><b>Offer</b>: %{x}<br>',
    marker=dict(
        color='pink',
        line=dict(
            color='grey',
            width=1.5),
        ),
    opacity=0.6
)

trace2 = go.Bar(
    x=x,
    y=y2,
    name='Male',
    #hoverinfo = 'y',
    hovertemplate = '<i>Percentage of all Male Customers who completed the Offer</i>: %{y:.2f}%'
                    '<br><b>Offer</b>: %{x}<br>',
    marker=dict(
        color='cornflowerblue',
        line=dict(
            color='grey',
            width=1.5),
        ),
    opacity=0.6
)



trace3 = go.Scatter(
    x=x,
    y=y3,
    name='Overall',
    #hoverinfo= 'y',
    hovertemplate = '<i>Percentage of all Customers, Male, Female, and Other who completed the Offer</i>: %{y:.2f}%'
                    '<br><b>Offer</b>: %{x}<br>',
    marker=dict(
        color='grey',
        )
)

data1 = [trace1, trace2, trace3]

layout = go.Layout(
    title = "Percentage of Completed offers by Gender",
    xaxis=dict(title = 'Offers',
    type='category'),
    barmode='group',
    yaxis = dict(title = 'Percentage of Completed offers'
        #hoverformat = '.2f'
    )
)

fig = go.Figure(data=data1, layout=layout)
py.iplot(fig, filename='Percentage of Completed offers by Gender')

/Users/Saleh/anaconda3/lib/python3.7/site-packages/IPython/core/display.py:689: UserWarning:

Consider using IPython.display.IFrame instead



The bar chart illustrates the numbers found earlier where we can see a clear difference between female customers’ behavior toward offers and the male customers’ behavior. Overall, offer 8 is the least popular offer, and offer 5 is the most popular offer for both gender. Offer 8 is the least popular offer for female customers and offer 3 is the least popular for male customers.


#### <font color=blue> 2.2.4 Offers

In [55]:
offers_list = full_data.drop_duplicates(subset=['offer_id'], keep='first')
offers_list = offers_list.drop(['customer_id', 
                                'age', 
                                'gender', 
                                'membership_start', 'membership_period', 
                                'transaction_amount', 'time_of_transaction(hours)',
                                'event', 
                                'income', 
                                'time(hours)_y',
                                'offer_views(%)',
                                'completed(not_viewed)'], axis=1)
offers_list.set_index('offer_id')

received  viewed  completed  offer_completion(%) offer_type  \
offer_id                                                                
1             6685    3499       4188            62.647719       bogo   
2             6683    5901       3657            54.720934       bogo   
3             6576    6310       4103            62.393552       bogo   
4             6631    3460       3911            58.980546   discount   
5             6652    6407       5003            75.210463   discount   
6             6655    6379       4886            73.418482   discount   
7             6726    2215       3386            50.341957   discount   
8             6593    6329       3310            50.204763       bogo   

          difficulty($)  duration(hours)  reward  email  mobile  social  web  
offer_id                                                                      
1                     5              168       5      1       1       0    1  
2                    10              168      10      1       1       1    0  
3                     5              120       5      1       1       1    1  
4                    10              168       2      1       1       0    1  
5                    10              240       2      1       1       1    1  
6                     7              168       3      1       1       1    1  
7                    20              240       5      1       0       0    1  
8                    10              120      10      1       1       1    1

In [56]:
offers_list[offers_list.offer_type == 'bogo'].set_index('offer_id')

received  viewed  completed  offer_completion(%) offer_type  \
offer_id                                                                
1             6685    3499       4188            62.647719       bogo   
2             6683    5901       3657            54.720934       bogo   
3             6576    6310       4103            62.393552       bogo   
8             6593    6329       3310            50.204763       bogo   

          difficulty($)  duration(hours)  reward  email  mobile  social  web  
offer_id                                                                      
1                     5              168       5      1       1       0    1  
2                    10              168      10      1       1       1    0  
3                     5              120       5      1       1       1    1  
8                    10              120      10      1       1       1    1

In [57]:
offers_list[offers_list.offer_type == 'discount'].set_index('offer_id')

received  viewed  completed  offer_completion(%) offer_type  \
offer_id                                                                
4             6631    3460       3911            58.980546   discount   
5             6652    6407       5003            75.210463   discount   
6             6655    6379       4886            73.418482   discount   
7             6726    2215       3386            50.341957   discount   

          difficulty($)  duration(hours)  reward  email  mobile  social  web  
offer_id                                                                      
4                    10              168       2      1       1       0    1  
5                    10              240       2      1       1       1    1  
6                     7              168       3      1       1       1    1  
7                    20              240       5      1       0       0    1

In [58]:
# function to return an analysis of the numbers and percentage of all transaction by offer
def analysis2(df1, col1, col2, col3, offer):
    v = df1[df1['event'] == 'offer viewed']
    v = v.drop_duplicates(subset=['customer_id', 'offer_id'], keep='first')

    c = df1[df1['event'] == 'offer completed']
    c = c.drop_duplicates(subset=['customer_id', 'offer_id'], keep='first')

    received = df1.drop_duplicates(subset=['customer_id', 'offer_id'], keep='first')

    viewed = pd.Series(v.age).value_counts().reset_index().rename(columns={'index': 'age_v', 'age': 'viewed'})
    completed = pd.Series(c.age).value_counts().reset_index().rename(columns={'index': 'age_c', 'age': 'completed'})
    received = pd.Series(received.age).value_counts().reset_index().rename(columns={'index': 'age_r', 'age': 'received'})


    analysis2 = pd.concat([viewed, completed, received], axis=1).rename(columns={'age_v': 'age', 'viewed': col2, 'completed': col3, 'received': col1})
    analysis2['offer'+offer+'_'+col2+'(%)'] = round(analysis2[col2]/analysis2[col1]*100, 2)
    analysis2['offer'+offer+'_'+col3+'(%)'] = round(analysis2[col3]/analysis2[col1]*100, 2)

    analysis2 = analysis2.drop(['age_r', 'age_c'], axis=1).sort_values(by='age')
    
    return analysis2

# function to return dataframe grouped by the time when each transaction takes a place from the start of an offer
# showing a description of the amount spent by that time
def offer_transcations(offer):
    offer_trans = transcation_by_time(df_completed, 'offer_id', offer)
    
    return offer_trans

# function to plot a trend of any two offers that shows the average Amount Spent since a Start of an Offer at a specific time
def plot2(offer1, offer2):
    offer_trans1 = offer_transcations(offer1)
    offer_trans2 = offer_transcations(offer2)
    
    trace_mean1 = go.Scatter(
        x=offer_trans1['time_of_transaction(hours)'],
        y=offer_trans1['mean'],
        name = offer1,
        opacity = 0.6)
    trace_mean2 = go.Scatter(
        x=offer_trans2['time_of_transaction(hours)'],
        y=offer_trans2['mean'],
        name = offer2,
        opacity = 0.6)


    data1 = [trace_mean1, trace_mean2]

    layout = {
        'title': 'Average Amount Spent Since a Start of an Offer Trend',
        'xaxis': {'title': 'Time Since a Start of an Offer (hours)'},
        'yaxis': {'title': 'Average Amount ($)', 
                  "range": [
                    10,
                    35
                ]}}
        
    fig = dict(data=data1, layout=layout)
    plot2 = py.iplot(fig, filename = "Amount Spent since a Start of an Offer Trend by Offer")
    
    return plot2

In [59]:
# showing a description of the amount spent by the time of transactions

offer_transcations(1)

time_of_transaction(hours)  count       mean   min     50%     max
0                            0  176.0  16.762386  0.16  15.185  195.24
1                            6  190.0  18.077684  0.07  14.780  448.97
2                           12  260.0  18.776923  0.21  15.565  639.59
3                           18  252.0  15.691270  0.13  13.245  366.65
4                           24  261.0  15.152414  0.07  13.770   42.30
5                           30  308.0  15.146201  0.12  12.870  323.88
6                           36  289.0  16.060796  0.05  13.990  400.74
7                           42  325.0  18.911662  0.18  13.100  657.26
8                           48  310.0  17.156097  0.09  14.725  475.20
9                           54  267.0  14.922097  0.43  12.740  347.37
10                          60  300.0  20.454800  0.41  13.920  713.20
11                          66  324.0  15.668117  0.05  15.345   39.36
12                          72  331.0  14.888429  0.13  13.590  115.31
13                          78  288.0  14.136771  0.41  12.540  105.24
14                          84  285.0  15.462807  0.80  13.740  251.32
15                          90  288.0  20.470069  0.42  13.870  841.06
16                          96  293.0  17.823993  0.08  15.160  370.89
17                         102  293.0  14.882287  0.11  14.090   78.23
18                         108  257.0  14.047354  0.42  12.880   42.08
19                         114  270.0  15.173630  0.31  15.050   39.35
20                         120  279.0  15.343297  0.08  14.140  232.89
21                         126  237.0  15.280338  0.19  14.180   37.97
22                         132  231.0  16.284416  0.14  14.700  277.53
23                         138  260.0  13.935192  0.19  12.860   42.74
24                         144  257.0  15.739066  0.16  14.780  115.64
25                         150  219.0  13.937489  0.11  14.670   39.61
26                         156  226.0  16.077611  0.14  14.350  367.37
27                         162  263.0  14.659962  0.20  13.360   91.10
28                         168  294.0  17.891463  0.26  14.215  881.35

In [60]:
# plotting and comparing the trend of any two offers

plot2(5, 7)

The bar chart illustrates the numbers found earlier where we can see a clear difference between female customers’ behavior toward offers and the male customers’ behavior. Overall, offer 8 is the least popular offer, and offer 5 is the most popular offer for both gender. Offer 8 is the least popular offer for female customers and offer 3 is the least popular for male customers.

In [61]:
# creating a dataframe that contains only transactions by a specific offer

offer1 = offer_dataset(full_data, 1)
offer1.sample(3)

customer_id  age gender   income membership_start membership_period  \
21683           929   29      F  61000.0       2017-09-18           2017-09   
22075           946   82      F  62000.0       2016-09-19           2016-09   
120747         5201   24      M  36000.0       2016-05-25           2016-05   

        transaction_amount  time_of_transaction(hours)            event  \
21683                16.05                          66  offer completed   
22075                 5.76                          36   offer received   
120747                3.08                          72   offer received   

        offer_id  ...  offer_completion(%)  completed(not_viewed)  offer_type  \
21683          1  ...            62.647719                    689        bogo   
22075          1  ...            62.647719                    689        bogo   
120747         1  ...            62.647719                    689        bogo   

        difficulty($)  duration(hours)  reward  email mobile  social  web  
21683               5              168       5      1      1       0    1  
22075               5              168       5      1      1       0    1  
120747              5              168       5      1      1       0    1  

[3 rows x 25 columns]

In [62]:
# showing the numbers and percentages of all transactions made by a specific age for a specific offer

offer1_analysis = analysis2(offer1, 'received', 'viewed', 'completed', '1')
offer1_analysis

age  viewed  completed  received  offer1_viewed(%)  offer1_completed(%)
68   18.0     9.0       12.0        16             56.25                75.00
60   19.0    13.0       19.0        30             43.33                63.33
56   20.0    15.0       22.0        33             45.45                66.67
57   21.0    14.0       21.0        31             45.16                67.74
58   22.0    14.0       20.0        30             46.67                66.67
61   23.0    13.0       17.0        28             46.43                60.71
52   24.0    18.0       25.0        37             48.65                67.57
62   25.0    12.0       17.0        28             42.86                60.71
49   26.0    19.0       27.0        38             50.00                71.05
42   27.0    21.0       29.0        42             50.00                69.05
64   28.0    12.0       15.0        20             60.00                75.00
54   29.0    16.0       24.0        36             44.44                66.67
46   30.0    20.0       28.0        41             48.78                68.29
63   31.0    12.0       15.0        24             50.00                62.50
44   32.0    20.0       28.0        41             48.78                68.29
45   33.0    20.0       28.0        41             48.78                68.29
43   34.0    21.0       29.0        42             50.00                69.05
51   35.0    18.0       25.0        37             48.65                67.57
37   36.0    26.0       33.0        49             53.06                67.35
27   37.0    34.0       39.0        56             60.71                69.64
33   38.0    31.0       37.0        53             58.49                69.81
26   39.0    35.0       40.0        56             62.50                71.43
24   40.0    36.0       42.0        57             63.16                73.68
25   41.0    35.0       41.0        57             61.40                71.93
23   42.0    37.0       44.0        59             62.71                74.58
35   43.0    30.0       36.0        50             60.00                72.00
20   44.0    40.0       48.0        62             64.52                77.42
14   45.0    44.0       56.0        74             59.46                75.68
22   46.0    38.0       46.0        61             62.30                75.41
38   47.0    25.0       32.0        47             53.19                68.09
..    ...     ...        ...       ...               ...                  ...
18   71.0    40.0       49.0        64             62.50                76.56
36   72.0    27.0       35.0        49             55.10                71.43
21   73.0    38.0       47.0        62             61.29                75.81
34   74.0    30.0       36.0        51             58.82                70.59
39   75.0    24.0       31.0        46             52.17                67.39
48   76.0    20.0       27.0        40             50.00                67.50
40   77.0    23.0       30.0        44             52.27                68.18
50   78.0    18.0       27.0        38             47.37                71.05
41   79.0    23.0       29.0        42             54.76                69.05
53   80.0    16.0       24.0        37             43.24                64.86
47   81.0    20.0       27.0        40             50.00                67.50
59   82.0    13.0       20.0        30             43.33                66.67
55   83.0    16.0       22.0        34             47.06                64.71
65   84.0    11.0       15.0        20             55.00                75.00
71   85.0     7.0        9.0        13             53.85                69.23
70   86.0     8.0       10.0        13             61.54                76.92
66   87.0    10.0       15.0        18             55.56                83.33
69   88.0     8.0       11.0        14             57.14                78.57
74   89.0     6.0        7.0        11             54.55                63.64
67   90.0     9.0       13.0

In [63]:
offer2 = offer_dataset(full_data, 2)
offer2.sample(3)

customer_id  age gender   income membership_start membership_period  \
165927         6404   53      F  34000.0       2017-03-11           2017-03   
143716          666   61      F  50000.0       2016-08-28           2016-08   
263125         8734   30      M  51000.0       2015-11-28           2015-11   

        transaction_amount  time_of_transaction(hours)            event  \
165927                8.67                          18  offer completed   
143716               14.24                          24  offer completed   
263125               18.58                          54   offer received   

        offer_id  ...  offer_completion(%)  completed(not_viewed)  offer_type  \
165927         2  ...            54.720934                  -2244        bogo   
143716         2  ...            54.720934                  -2244        bogo   
263125         2  ...            54.720934                  -2244        bogo   

        difficulty($)  duration(hours)  reward  email mobile  social  web  
165927             10              168      10      1      1       1    0  
143716             10              168      10      1      1       1    0  
263125             10              168      10      1      1       1    0  

[3 rows x 25 columns]

In [64]:
offer2_analysis = analysis2(offer2, 'received', 'viewed', 'completed', '2')
offer2_analysis

age  viewed  completed  received  offer2_viewed(%)  offer2_completed(%)
69   18      16          8        18             88.89                44.44
57   19      32         17        33             96.97                51.52
42   20      42         25        44             95.45                56.82
53   21      33         18        34             97.06                52.94
55   22      33         17        33            100.00                51.52
49   23      35         19        39             89.74                48.72
47   24      38         20        41             92.68                48.78
39   25      46         27        47             97.87                57.45
40   26      45         26        47             95.74                55.32
54   27      33         18        33            100.00                54.55
44   28      41         23        42             97.62                54.76
38   29      46         27        48             95.83                56.25
52   30      34         18        35             97.14                51.43
67   31      17          9        18             94.44                50.00
35   32      50         30        52             96.15                57.69
45   33      39         22        42             92.86                52.38
36   34      49         28        52             94.23                53.85
43   35      41         25        44             93.18                56.82
37   36      48         28        50             96.00                56.00
28   37      55         37        60             91.67                61.67
32   38      52         33        56             92.86                58.93
29   39      54         36        59             91.53                61.02
19   40      63         43        68             92.65                63.24
31   41      52         33        56             92.86                58.93
21   42      59         40        67             88.06                59.70
27   43      56         37        61             91.80                60.66
48   44      38         19        40             95.00                47.50
17   45      64         47        72             88.89                65.28
24   46      57         39        62             91.94                62.90
26   47      56         38        61             91.80                62.30
..  ...     ...        ...       ...               ...                  ...
34   69      51         30        54             94.44                55.56
33   70      52         31        54             96.30                57.41
25   71      56         39        62             90.32                62.90
41   72      43         26        46             93.48                56.52
22   73      58         39        66             87.88                59.09
46   74      39         20        41             95.12                48.78
50   75      35         19        37             94.59                51.35
59   76      27         14        32             84.38                43.75
56   77      32         17        33             96.97                51.52
51   78      35         18        36             97.22                50.00
62   79      24         14        27             88.89                51.85
63   80      24         14        27             88.89                51.85
60   81      25         14        30             83.33                46.67
61   82      25         14        29             86.21                48.28
58   83      29         15        32             90.62                46.88
64   84      21         11        21            100.00                52.38
68   85      16          9        18             88.89                50.00
74   86      10          7        10            100.00                70.00
66   87      17         10        18             94.44                55.56
71   88      12          8        13             92.31                61.54
65   89      17         10        18             94.

In [65]:
offer3 = offer_dataset(full_data, 3)
offer3_analysis = analysis2(offer3, 'received', 'viewed', 'completed', '3')
offer3_analysis

age  viewed  completed  received  offer3_viewed(%)  offer3_completed(%)
68   18      17         13        17            100.00                76.47
41   19      37         27        38             97.37                71.05
44   20      35         25        36             97.22                69.44
40   21      37         27        38             97.37                71.05
55   22      29         21        30             96.67                70.00
43   23      36         25        38             94.74                65.79
52   24      32         22        33             96.97                66.67
47   25      33         23        35             94.29                65.71
28   26      46         34        47             97.87                72.34
45   27      35         25        36             97.22                69.44
42   28      37         26        38             97.37                68.42
37   29      38         28        40             95.00                70.00
46   30      34         24        36             94.44                66.67
64   31      19         16        19            100.00                84.21
51   32      33         23        34             97.06                67.65
60   33      26         17        27             96.30                62.96
49   34      33         23        35             94.29                65.71
59   35      27         18        28             96.43                64.29
53   36      30         21        32             93.75                65.62
26   37      46         36        49             93.88                73.47
36   38      40         29        41             97.56                70.73
35   39      40         29        42             95.24                69.05
23   40      51         41        52             98.08                78.85
22   41      51         41        52             98.08                78.85
34   42      41         31        43             95.35                72.09
29   43      46         34        47             97.87                72.34
27   44      46         34        48             95.83                70.83
18   45      62         46        62            100.00                74.19
30   46      46         33        47             97.87                70.21
33   47      41         31        43             95.35                72.09
..  ...     ...        ...       ...               ...                  ...
39   72      37         27        40             92.50                67.50
32   73      43         33        45             95.56                73.33
31   74      45         33        46             97.83                71.74
58   75      27         19        29             93.10                65.52
50   76      33         23        34             97.06                67.65
54   77      30         21        32             93.75                65.62
61   78      23         17        26             88.46                65.38
57   79      28         20        29             96.55                68.97
48   80      33         23        35             94.29                65.71
56   81      29         20        30             96.67                66.67
63   82      21         16        22             95.45                72.73
62   83      22         17        22            100.00                77.27
66   84      19         13        19            100.00                68.42
67   85      17         13        18             94.44                72.22
65   86      19         15        19            100.00                78.95
70   87      14         12        14            100.00                85.71
69   88      15         13        15            100.00                86.67
76   89       7          6         7            100.00                85.71
74   90       8          8         8            100.00               100.00
72   91      11          9        11            100.00                81.82
71   92      11         11        12             91.

In [66]:
offer4 = offer_dataset(full_data, 4)
offer4_analysis = analysis2(offer4, 'received', 'viewed', 'completed', '4')
offer4_analysis

age  viewed  completed  received  offer4_viewed(%)  offer4_completed(%)
71   18.0     6.0          9        12             50.00                75.00
64   19.0    11.0         13        23             47.83                56.52
54   20.0    15.0         20        33             45.45                60.61
50   21.0    16.0         21        37             43.24                56.76
59   22.0    13.0         17        29             44.83                58.62
49   23.0    16.0         22        38             42.11                57.89
44   24.0    18.0         24        42             42.86                57.14
60   25.0    12.0         17        28             42.86                60.71
58   26.0    13.0         17        29             44.83                58.62
57   27.0    13.0         17        29             44.83                58.62
56   28.0    14.0         18        30             46.67                60.00
48   29.0    17.0         22        39             43.59                56.41
51   30.0    16.0         21        36             44.44                58.33
47   31.0    18.0         24        40             45.00                60.00
42   32.0    19.0         25        43             44.19                58.14
46   33.0    18.0         24        42             42.86                57.14
41   34.0    20.0         26        43             46.51                60.47
66   35.0    10.0         13        19             52.63                68.42
40   36.0    23.0         26        44             52.27                59.09
39   37.0    25.0         29        44             56.82                65.91
25   38.0    37.0         38        59             62.71                64.41
21   39.0    39.0         46        63             61.90                73.02
28   40.0    35.0         37        55             63.64                67.27
32   41.0    31.0         35        52             59.62                67.31
22   42.0    37.0         45        62             59.68                72.58
31   43.0    32.0         35        52             61.54                67.31
30   44.0    32.0         36        53             60.38                67.92
14   45.0    45.0         54        71             63.38                76.06
26   46.0    36.0         38        58             62.07                65.52
20   47.0    39.0         46        64             60.94                71.88
..    ...     ...        ...       ...               ...                  ...
36   72.0    27.0         33        49             55.10                67.35
33   73.0    30.0         34        51             58.82                66.67
35   74.0    28.0         34        49             57.14                69.39
37   75.0    26.0         33        48             54.17                68.75
38   76.0    25.0         29        47             53.19                61.70
52   77.0    16.0         20        35             45.71                57.14
43   78.0    19.0         25        43             44.19                58.14
45   79.0    18.0         24        42             42.86                57.14
61   80.0    12.0         16        27             44.44                59.26
55   81.0    14.0         19        31             45.16                61.29
63   82.0    11.0         13        24             45.83                54.17
53   83.0    15.0         20        35             42.86                57.14
62   84.0    12.0         14        25             48.00                56.00
65   85.0    11.0         13        22             50.00                59.09
67   86.0     9.0         12        18             50.00                66.67
72   87.0     5.0          8        12             41.67                66.67
68   88.0     8.0         12        17             47.06                70.59
70   89.0     6.0         10        15             40.00                66.67
76   90.0     3.0          5         6             50.00                83.33
74   91.0     4.0          6

In [67]:
offer5 = offer_dataset(full_data, 5)
offer5_analysis = analysis2(offer5, 'received', 'viewed', 'completed', '5')
offer5_analysis

age  viewed  completed  received  offer5_viewed(%)  offer5_completed(%)
66   18      21         19        22             95.45                86.36
53   19      40         31        41             97.56                75.61
61   20      31         25        32             96.88                78.12
41   21      49         40        53             92.45                75.47
49   22      42         33        44             95.45                75.00
48   23      42         34        44             95.45                77.27
55   24      38         30        40             95.00                75.00
44   25      46         38        49             93.88                77.55
39   26      54         43        56             96.43                76.79
40   27      53         43        55             96.36                78.18
47   28      44         34        44            100.00                77.27
57   29      37         29        39             94.87                74.36
50   30      42         33        42            100.00                78.57
58   31      36         28        37             97.30                75.68
51   32      41         32        42             97.62                76.19
45   33      46         37        48             95.83                77.08
30   34      58         49        60             96.67                81.67
56   35      38         29        40             95.00                72.50
27   36      61         52        63             96.83                82.54
38   37      55         44        57             96.49                77.19
33   38      57         49        59             96.61                83.05
35   39      57         48        58             98.28                82.76
24   40      65         54        66             98.48                81.82
32   41      58         49        59             98.31                83.05
29   42      60         50        62             96.77                80.65
23   43      70         54        71             98.59                76.06
42   44      48         39        50             96.00                78.00
21   45      72         56        75             96.00                74.67
37   46      57         44        58             98.28                75.86
22   47      72         54        72            100.00                75.00
..  ...     ...        ...       ...               ...                  ...
26   71      62         52        64             96.88                81.25
34   72      57         49        59             96.61                83.05
25   73      63         52        65             96.92                80.00
31   74      58         49        60             96.67                81.67
54   75      40         30        41             97.56                73.17
46   76      45         35        45            100.00                77.78
62   77      31         25        32             96.88                78.12
43   78      47         39        49             95.92                79.59
63   79      29         23        29            100.00                79.31
52   80      40         32        42             95.24                76.19
64   81      26         22        28             92.86                78.57
60   82      33         27        34             97.06                79.41
59   83      34         28        35             97.14                80.00
68   84      16         14        18             88.89                77.78
67   85      19         18        21             90.48                85.71
75   86      10         10        11             90.91                90.91
65   87      22         20        23             95.65                86.96
74   88      11         10        12             91.67                83.33
70   89      14         12        14            100.00                85.71
69   90      15         14        15            100.00                93.33
71   91      14         12        14            100.

In [68]:
offer6 = offer_dataset(full_data, 6)
offer6_analysis = analysis2(offer6, 'received', 'viewed', 'completed', '6')
offer6_analysis

age  viewed  completed  received  offer6_viewed(%)  offer6_completed(%)
66   18      21       19.0        23             91.30                82.61
45   19      43       34.0        44             97.73                77.27
56   20      33       25.0        33            100.00                75.76
47   21      40       33.0        41             97.56                80.49
50   22      38       31.0        39             97.44                79.49
51   23      37       29.0        38             97.37                76.32
48   24      39       32.0        41             95.12                78.05
52   25      36       28.0        38             94.74                73.68
43   26      44       36.0        45             97.78                80.00
38   27      46       39.0        47             97.87                82.98
34   28      51       42.0        53             96.23                79.25
46   29      41       33.0        42             97.62                78.57
59   30      30       24.0        30            100.00                80.00
61   31      29       22.0        30             96.67                73.33
58   32      31       24.0        32             96.88                75.00
54   33      36       26.0        36            100.00                72.22
42   34      44       37.0        45             97.78                82.22
40   35      45       38.0        46             97.83                82.61
31   36      53       45.0        54             98.15                83.33
20   37      59       52.0        61             96.72                85.25
28   38      54       47.0        56             96.43                83.93
37   39      46       39.0        48             95.83                81.25
27   40      55       48.0        57             96.49                84.21
35   41      48       41.0        50             96.00                82.00
30   42      53       45.0        54             98.15                83.33
23   43      57       50.0        60             95.00                83.33
41   44      45       37.0        46             97.83                80.43
22   45      58       50.0        60             96.67                83.33
33   46      52       42.0        53             98.11                79.25
29   47      54       46.0        55             98.18                83.64
..  ...     ...        ...       ...               ...                  ...
26   71      56       48.0        58             96.55                82.76
39   72      45       38.0        47             95.74                80.85
36   73      47       40.0        49             95.92                81.63
32   74      52       44.0        54             96.30                81.48
44   75      43       35.0        45             95.56                77.78
49   76      38       32.0        40             95.00                80.00
60   77      30       23.0        30            100.00                76.67
57   78      32       25.0        33             96.97                75.76
63   79      24       21.0        25             96.00                84.00
62   80      25       22.0        25            100.00                88.00
55   81      33       25.0        34             97.06                73.53
53   82      36       28.0        37             97.30                75.68
65   83      21       21.0        23             91.30                91.30
64   84      23       21.0        24             95.83                87.50
67   85      16       15.0        17             94.12                88.24
68   86      16       15.0        16            100.00                93.75
73   87      10        9.0        11             90.91                81.82
72   88      11        9.0        11            100.00                81.82
70   89      12       10.0        12            100.00                83.33
69   90      13       11.0        14             92.86                78.57
74   91       9        9.0         9            100.

In [69]:
offer7 = offer_dataset(full_data, 7)
offer7_analysis = analysis2(offer7, 'received', 'viewed', 'completed', '7')
offer7_analysis

age  viewed  completed  received  offer7_viewed(%)  offer7_completed(%)
68   18.0     6.0         11        19             31.58                57.89
72   19.0     5.0          8        12             41.67                66.67
58   20.0     7.0         17        34             20.59                50.00
65   21.0     6.0         12        26             23.08                46.15
66   22.0     6.0         11        24             25.00                45.83
45   23.0    11.0         23        47             23.40                48.94
44   24.0    12.0         24        48             25.00                50.00
50   25.0    10.0         20        44             22.73                45.45
62   26.0     7.0         13        31             22.58                41.94
67   27.0     6.0         11        22             27.27                50.00
47   28.0    10.0         22        45             22.22                48.89
63   29.0     7.0         12        26             26.92                46.15
53   30.0     9.0         19        41             21.95                46.34
57   31.0     8.0         17        36             22.22                47.22
51   32.0     9.0         19        43             20.93                44.19
49   33.0    10.0         20        44             22.73                45.45
69   34.0     6.0         11        17             35.29                64.71
56   35.0     8.0         19        37             21.62                51.35
41   36.0    13.0         26        50             26.00                52.00
32   37.0    24.0         32        60             40.00                53.33
40   38.0    17.0         29        50             34.00                58.00
21   39.0    30.0         42        74             40.54                56.76
18   40.0    33.0         45        79             41.77                56.96
37   41.0    19.0         30        53             35.85                56.60
28   42.0    26.0         37        62             41.94                59.68
35   43.0    21.0         31        57             36.84                54.39
22   44.0    29.0         41        74             39.19                55.41
11   45.0    37.0         60        90             41.11                66.67
30   46.0    25.0         35        61             40.98                57.38
20   47.0    30.0         42        76             39.47                55.26
..    ...     ...        ...       ...               ...                  ...
27   70.0    26.0         38        62             41.94                61.29
25   71.0    28.0         41        67             41.79                61.19
70   72.0     6.0         11        16             37.50                68.75
24   73.0    28.0         41        69             40.58                59.42
34   74.0    21.0         31        58             36.21                53.45
33   75.0    23.0         31        59             38.98                52.54
39   76.0    17.0         29        51             33.33                56.86
36   77.0    19.0         30        56             33.93                53.57
38   78.0    18.0         30        52             34.62                57.69
48   79.0    10.0         21        45             22.22                46.67
43   80.0    13.0         24        49             26.53                48.98
42   81.0    13.0         25        49             26.53                51.02
60   82.0     7.0         16        32             21.88                50.00
61   83.0     7.0         16        31             22.58                51.61
46   84.0    11.0         22        47             23.40                46.81
55   85.0     8.0         19        38             21.05                50.00
74   86.0     3.0          7        11             27.27                63.64
64   87.0     7.0         12        26             26.92                46.15
54   88.0     9.0         19        38             23.68                50.00
59   89.0     7.0         17

In [70]:
offer8 = offer_dataset(full_data, 8)
offer8_analysis = analysis2(offer8, 'received', 'viewed', 'completed', '8')
offer8_analysis

age  viewed  completed  received  offer8_viewed(%)  offer8_completed(%)
64   18      20       10.0        20            100.00                50.00
41   19      38       18.0        39             97.44                46.15
55   20      29       14.0        30             96.67                46.67
38   21      39       22.0        40             97.50                55.00
57   22      28       13.0        29             96.55                44.83
40   23      38       19.0        40             95.00                47.50
45   24      35       16.0        38             92.11                42.11
46   25      35       16.0        37             94.59                43.24
39   26      38       22.0        40             95.00                55.00
32   27      42       26.0        42            100.00                61.90
58   28      27       12.0        28             96.43                42.86
37   29      39       23.0        41             95.12                56.10
51   30      32       14.0        32            100.00                43.75
60   31      25       12.0        27             92.59                44.44
42   32      37       18.0        39             94.87                46.15
52   33      32       14.0        32            100.00                43.75
54   34      31       14.0        31            100.00                45.16
56   35      28       13.0        29             96.55                44.83
36   36      40       23.0        41             97.56                56.10
30   37      43       27.0        45             95.56                60.00
26   38      50       31.0        51             98.04                60.78
33   39      41       25.0        42             97.62                59.52
31   40      42       27.0        42            100.00                64.29
43   41      36       17.0        39             92.31                43.59
15   42      61       39.0        61            100.00                63.93
20   43      57       35.0        58             98.28                60.34
28   44      47       29.0        50             94.00                58.00
22   45      52       33.0        56             92.86                58.93
27   46      48       29.0        50             96.00                58.00
35   47      40       23.0        41             97.56                56.10
..  ...     ...        ...       ...               ...                  ...
21   71      55       34.0        57             96.49                59.65
53   72      31       14.0        32             96.88                43.75
47   73      35       15.0        36             97.22                41.67
34   74      41       24.0        42             97.62                57.14
48   75      33       15.0        35             94.29                42.86
44   76      36       17.0        38             94.74                44.74
59   77      26       12.0        28             92.86                42.86
50   78      32       14.0        32            100.00                43.75
69   79      13        7.0        14             92.86                50.00
49   80      32       14.0        34             94.12                41.18
61   81      24       11.0        24            100.00                45.83
63   82      21       11.0        21            100.00                52.38
62   83      22       11.0        22            100.00                50.00
66   84      17       10.0        17            100.00                58.82
65   85      18       10.0        18            100.00                55.56
72   86      10        5.0        10            100.00                50.00
68   87      16        8.0        17             94.12                47.06
67   88      17       10.0        17            100.00                58.82
71   89      10        5.0        11             90.91                45.45
70   90      11        6.0        11            100.00                54.55
75   91       7        4.0         7            100.

In [71]:
# merging all the analyses created for each offer and then create a dataframe shows the completion percentage 
# of each offer based on the age group

completion_perc_o = pd.merge(pd.merge(pd.merge(pd.merge(pd.merge(pd.merge(pd.merge(offer1_analysis, offer2_analysis, on='age'), 
                             offer3_analysis, on='age'),
                             offer4_analysis, on='age'),
                             offer5_analysis, on='age'),
                             offer6_analysis, on='age'),
                             offer7_analysis, on='age'),
                             offer8_analysis, on='age')
col_list = ['age', 
            'offer1_completed(%)', 
            'offer2_completed(%)', 
            'offer3_completed(%)', 
            'offer4_completed(%)', 
            'offer5_completed(%)', 
            'offer6_completed(%)', 
            'offer7_completed(%)', 
            'offer8_completed(%)']
completion_perc_o = completion_perc_o[col_list]
completion_perc_o

age  offer1_completed(%)  offer2_completed(%)  offer3_completed(%)  \
0   18.0                75.00                44.44                76.47   
1   19.0                63.33                51.52                71.05   
2   20.0                66.67                56.82                69.44   
3   21.0                67.74                52.94                71.05   
4   22.0                66.67                51.52                70.00   
5   23.0                60.71                48.72                65.79   
6   24.0                67.57                48.78                66.67   
7   25.0                60.71                57.45                65.71   
8   26.0                71.05                55.32                72.34   
9   27.0                69.05                54.55                69.44   
10  28.0                75.00                54.76                68.42   
11  29.0                66.67                56.25                70.00   
12  30.0                68.29                51.43                66.67   
13  31.0                62.50                50.00                84.21   
14  32.0                68.29                57.69                67.65   
15  33.0                68.29                52.38                62.96   
16  34.0                69.05                53.85                65.71   
17  35.0                67.57                56.82                64.29   
18  36.0                67.35                56.00                65.62   
19  37.0                69.64                61.67                73.47   
20  38.0                69.81                58.93                70.73   
21  39.0                71.43                61.02                69.05   
22  40.0                73.68                63.24                78.85   
23  41.0                71.93                58.93                78.85   
24  42.0                74.58                59.70                72.09   
25  43.0                72.00                60.66                72.34   
26  44.0                77.42                47.50                70.83   
27  45.0                75.68                65.28                74.19   
28  46.0                75.41                62.90                70.21   
29  47.0                68.09                62.30                72.09   
..   ...                  ...                  ...                  ...   
48  66.0                76.81                66.27                76.47   
49  67.0                76.25                62.82                78.08   
50  68.0                70.37                61.19                72.00   
51  69.0                70.91                55.56                78.43   
52  70.0                70.37                57.41                73.33   
53  71.0                76.56                62.90                67.50   
54  72.0                71.43                56.52                67.50   
55  73.0                75.81                59.09                73.33   
56  74.0                70.59                48.78                71.74   
57  75.0                67.39                51.35                65.52   
58  76.0                67.50                43.75                67.65   
59  77.0                68.18                51.52                65.62   
60  78.0                71.05                50.00                65.38   
61  79.0                69.05                51.85                68.97   
62  80.0                64.86                51.85                65.71   
63  81.0                67.50                46.67                66.67   
64  82.0                66.67                48.28                72.73   
65  83.0                64.71                46.88                77.27   
66  84.0                75.00                52.38                68.42   
67  85.0                69.23                50.00                72.22   
68  86.0                76.92                70.00                78.95   
69  87.0                83.33 

A complete analysis of each offer was created to show the completion rate of each age group with respect to an offer. The following function will allow us to report the completion rates per age group. Then, we will plot a trend of the completion rates by each age group for each offer.

In [72]:
# a function to return a report of an age group that contains all completion percentages by offer

def age_report(a, df=completion_perc_o):
    report = df[df.age == a]
    
    return report

In [73]:
age_report(35)

age  offer1_completed(%)  offer2_completed(%)  offer3_completed(%)  \
17  35.0                67.57                56.82                64.29   

    offer4_completed(%)  offer5_completed(%)  offer6_completed(%)  \
17                68.42                 72.5                82.61   

    offer7_completed(%)  offer8_completed(%)  
17                51.35                44.83

In [74]:
age_report(40)

age  offer1_completed(%)  offer2_completed(%)  offer3_completed(%)  \
22  40.0                73.68                63.24                78.85   

    offer4_completed(%)  offer5_completed(%)  offer6_completed(%)  \
22                67.27                81.82                84.21   

    offer7_completed(%)  offer8_completed(%)  
22                56.96                64.29

In [75]:
age_report(25)

age  offer1_completed(%)  offer2_completed(%)  offer3_completed(%)  \
7  25.0                60.71                57.45                65.71   

   offer4_completed(%)  offer5_completed(%)  offer6_completed(%)  \
7                60.71                77.55                73.68   

   offer7_completed(%)  offer8_completed(%)  
7                45.45                43.24

In [76]:
# creating a copy of the completion reports 

plot1 = completion_perc_o.copy()

# plotting the Percentages of Completed offers by each Age group for each offer

plot1 = plot1.set_index('age')

trace1 = go.Scatter(
    x=plot1.index,
    y=plot1['offer1_completed(%)'],
    name = "Offer 1",
    opacity = 0.8)

trace2 = go.Scatter(
    x=plot1.index,
    y=plot1['offer2_completed(%)'],
    name = "Offer 2",
    opacity = 0.8)

trace3 = go.Scatter(
    x=plot1.index,
    y=plot1['offer3_completed(%)'],
    name = "Offer 3",
    opacity = 0.8)

trace4 = go.Scatter(
    x=plot1.index,
    y=plot1['offer4_completed(%)'],
    name = "Offer 4",
    opacity = 0.8)

trace5 = go.Scatter(
    x=plot1.index,
    y=plot1['offer5_completed(%)'],
    name = "Offer 5",
    opacity = 0.8)

trace6 = go.Scatter(
    x=plot1.index,
    y=plot1['offer6_completed(%)'],
    name = "Offer 6",
    opacity = 0.8)

trace7 = go.Scatter(
    x=plot1.index,
    y=plot1['offer7_completed(%)'],
    name = "Offer 7",
    opacity = 0.8)

trace8 = go.Scatter(
    x=plot1.index,
    y=plot1['offer8_completed(%)'],
    name = "Offer 8",
    opacity = 0.8)

data1 = [trace1, trace2, trace3, trace4, trace5, trace6, trace7, trace8]

layout = {
    'title': 'Percentage of Completed offers by Age',
    'xaxis': {'title': 'Age'},
    'yaxis': {'title': 'Percentage Completed (%)'}}

layout.update(dict(xaxis=dict(rangeslider=dict(visible = True),type='linear')))

updatemenus = list([
    dict(active=0,
         buttons=list([   
            dict(label = 'All',
                 method = 'update',
                 args = [{'visible': [True, True, True, True, True, True, True, True]},
                         {'title': 'Percentage of Each Completed offers by Age'}]),
            dict(label = 'Offer 1',
                 method = 'update',
                 args = [{'visible': [True, False, False, False, False, False, False, False]},
                         {'title': 'Percentage of Completed offers by Age for Offer 1'}]),
            dict(label = 'Offer 2',
                 method = 'update',
                 args = [{'visible': [False, True, False, False, False, False, False, False]},
                         {'title': 'Percentage of Completed offers by Age for Offer 2'}]),
            dict(label = 'Offer 3',
                 method = 'update',
                 args = [{'visible': [False, False, True, False, False, False, False, False]},
                         {'title': 'Percentage of Completed offers by Age for Offer 3'}]),
            dict(label = 'Offer 4',
                 method = 'update',
                 args = [{'visible': [False, False, False, True, False, False, False, False]},
                         {'title': 'Percentage of Completed offers by Age for Offer 4'}]),
            dict(label = 'Offer 5',
                 method = 'update',
                 args = [{'visible': [False, False, False, False, True, False, False, False]},
                         {'title': 'Percentage of Completed offers by Age for Offer 5'}]),
            dict(label = 'Offer 6',
                 method = 'update',
                 args = [{'visible': [False, False, False, False, False, True, False, False]},
                         {'title': 'Percentage of Completed offers by Age for Offer 6'}]),
            dict(label = 'Offer 7',
                 method = 'update',
                 args = [{'visible': [False, False, False, False, False, False, True, False]},
                         {'title': 'Percentage of Completed offers by Age for Offer 7'}]),
            dict(label = 'Offer 8',
                 method = 'update',
                 args = [{'visible': [False, False, False, False, False, False, False, True]},
                         {'title': 'Percentage of Completed offers by Age for Offer 8'}])
        ]),
         
    )
    
])


layout.update(dict(updatemenus=updatemenus))

fig = go.Figure(data=data1, layout=layout)

              
py.iplot(fig, filename = "Percentage of Completed offers by Age")

/Users/Saleh/anaconda3/lib/python3.7/site-packages/IPython/core/display.py:689: UserWarning:

Consider using IPython.display.IFrame instead



The plot illustrates the Percentages of Completed offers by each age group that can be filtered by offer. For example, at the age group 35 years old, offer 6 has the highest completion rate 82.61%. While the age group 25 years old prefer offer 5 the most with a completion rate of 77.55%.

In [77]:
fig.update_layout(
    updatemenus=[
        go.layout.Updatemenu(
            buttons=list([
                dict(
                    args=["colorscale", "Viridis"],
                    label="Viridis",
                    method="restyle"
                ),
                dict(
                    args=["colorscale", "Cividis"],
                    label="Cividis",
                    method="restyle"
                ),
                dict(
                    args=["colorscale", "Blues"],
                    label="Blues",
                    method="restyle"
                ),
                dict(
                    args=["colorscale", "Greens"],
                    label="Greens",
                    method="restyle"
                ),
            ]),
            direction="down",
            pad={"r": 10, "t": 10},
            showactive=True,
            x=0.1,
            xanchor="left",
            y=button_layer_1_height,
            yanchor="top"
        ),
        go.layout.Updatemenu(
            buttons=list([
                dict(
                    args=["reversescale", False],
                    label="False",
                    method="restyle"
                ),
                dict(
                    args=["reversescale", True],
                    label="True",
                    method="restyle"
                )
            ]),
            direction="down",
            pad={"r": 10, "t": 10},
            showactive=True,
            x=0.37,
            xanchor="left",
            y=button_layer_1_height,
            yanchor="top"
        ),
        go.layout.Updatemenu(
            buttons=list([
                dict(
                    args=[{"contours.showlines": False, "type": "contour"}],
                    label="Hide lines",
                    method="restyle"
                ),
                dict(
                    args=[{"contours.showlines": True, "type": "contour"}],
                    label="Show lines",
                    method="restyle"
                ),
            ]),
            direction="down",
            pad={"r": 10, "t": 10},
            showactive=True,
            x=0.58,
            xanchor="left",
            y=button_layer_1_height,
            yanchor="top"
        ),
    ]
)

AttributeError: 'Figure' object has no attribute 'update_layout'

### Bonus

In [78]:
# plotting a Sunburst Charts shows the numbers of customers
# with respect to all transactions where the the customers completed an offer 

trace = go.Sunburst(
    labels=["Transactions",
            "BOGO", "Discount",
            "Offer 1", "Offer 2", "Offer 3", "Offer 4", "Offer 5", 
            "Offer 6", "Offer 7", "Offer 8",
            "Female", "Male", "Other", 
            "Female", "Male", "Other",
            "Female", "Male", "Other", 
            "Female", "Male", "Other", 
            "Female", "Male", "Other", 
            "Female", "Male", "Other", 
            "Female", "Male", "Other", 
            "Female", "Male", "Other"],
    parents=["", 
             "Transactions", "Transactions", 
             "BOGO", "BOGO", "BOGO", "Discount", "Discount", 
             "Discount", "Discount", "BOGO",
             "Offer 1", "Offer 1", "Offer 1",
             "Offer 2", "Offer 2", "Offer 2", 
             "Offer 3", "Offer 3", "Offer 3",
             "Offer 4", "Offer 4", "Offer 4",
             "Offer 5", "Offer 5", "Offer 5",
             "Offer 6", "Offer 6", "Offer 6",
             "Offer 7", "Offer 7", "Offer 7",
             "Offer 8", "Offer 8", "Offer 8"],
    values=[26226, 
            9937, 12089,
            2573, 2773, 2374, 2499, 3729, 
            2592, 3269, 1917,
            1197, 1324, 52,
            1281, 1441, 51,
            1134, 917, 323,
            1247, 1252, 0,
            1626, 2052, 51,
            1188, 1354, 50,
            1371, 1755, 141,
            872, 1045, 0],
    branchvalues="total",
    outsidetextfont = {"size": 15, "color": "#377eb8"},
    marker = {"line": {"width": 2}})

layout = go.Layout(
    title = 'test',
    margin = go.layout.Margin(t=0, l=0, r=0, b=0))

py.iplot(go.Figure([trace], layout), filename='basic_sunburst_chart_total_branchvalues')

An interactive sunburst chart that shows more details about the number of transactions made where customers received an offer, viewed that offer through one of the channels used, and then made a transaction and completed the offer before the end of the duration of that offer.